customization:
  one_biome:
    biome: JUNGLE
    enabled: true
  tree_spawning:
    allowed_blocks:
    - GRASS_BLOCK
    - DIRT
    - COARSE_DIRT
    - PODZOL
    - SAND
    - SNOW_BLOCK
    - PACKED_ICE
    - ICE
  ocean:
    block: minecraft:water[level=0]
  flat_spawn:
    radius: 40
    fading: 20
    enabled: false
    height: 70
